name: "Publish ghcr (server)"

on:
    # Run manually if needed to publish out of schedule.
    workflow_dispatch:

permissions:
    contents: write  # for pushing the `ghcr/server` branch
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Build and push
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                  dockerfile: server/Dockerfile
                  directory: server
                  image: server
                  registry: ghcr.io
                  enableBuildKit: true
                  multiPlatform: true
                  platform: linux/amd64,linux/arm64
                  tags: latest
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Update branch ghcr/server to point to source commit
              run: |
                  git push -f origin HEAD:refs/heads/ghcr/server