name: "Publish ghcr (web)"

on:
    # Run manually if needed to publish out of schedule.
    workflow_dispatch:

permissions:
    contents: write  # for pushing the `ghcr/web` branch
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                  dockerfile: web/Dockerfile
                  directory: web
                  image: web
                  registry: ghcr.io
                  enableBuildKit: true
                  multiPlatform: true
                  platform: linux/amd64,linux/arm64
                  tags: ${{ github.sha }}, latest
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Update branch ghcr/web to point to source commit
              run: |
                  git push -f origin HEAD:refs/heads/ghcr/web
